name: EasyEdit
main: platz1de\EasyEdit\EasyEdit
api: 4.0.0
version: 2.1.1
author: platz1de
permissions:
  easyedit.edit:
    default: op
    description: "Allows the user to edit blocks"
  easyedit.generate:
    default: op
    description: "Allows the user to generate blocks"
  easyedit.history:
    default: op
    description: "Allows the user to use the edit history"
  easyedit.history.other:
    default: op
    description: "Allows the user to use the edit history of other people"
  easyedit.clipboard:
    default: op
    description: "Allows the user to use the clipboard"
  easyedit.readdisk:
    default: op
    description: "Allows the user to load schematics from disk"
  easyedit.writedisk:
    default: op
    description: "Allows the user to load schematics from disk"
  easyedit.manage:
    default: op
    description: "Allows the user to manage plugin internals"
  easyedit.select:
    default: op
    description: "Allows the user to select positions"
  easyedit.brush:
    default: op
    description: "Allows the user to use brushes"
  easyedit.rod:
    default: op
    description: "Allows the user to use the builder rod"
  easyedit.util:
    default: op
    description: "Allows the user to use utility tools"